# Generated by Django 3.0.5 on 2024-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('id_docteur', models.CharField(max_length=20, unique=True)),
                ('specialite', models.CharField(max_length=200)),
                ('numero_telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Malade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('adresse_naissance', models.CharField(max_length=200)),
                ('adresse_actuelle', models.CharField(max_length=200)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('numero_identite', models.CharField(max_length=20)),
                ('statut', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Other', 'Other')], max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('est_retraite', models.BooleanField(default=False)),
                ('contact_personnel', models.CharField(max_length=100)),
                ('numero_maison', models.CharField(max_length=10)),
                ('numero_deuxieme_personne', models.CharField(max_length=15)),
                ('nom_maladie_chronique', models.CharField(max_length=200)),
                ('description_maladie', models.TextField()),
                ('effets_maladie', models.TextField()),
                ('description_deuxieme_maladie', models.TextField(blank=True, null=True)),
                ('effets_deuxieme_maladie', models.TextField(blank=True, null=True)),
                ('analyse_maladie', models.FileField(upload_to='analyses/')),
                ('analyse_deuxieme_maladie', models.FileField(blank=True, null=True, upload_to='analyses/')),
                ('medicaments', models.TextField()),
                ('contact_medecin', models.CharField(max_length=200)),
            ],
        ),
    ]
